### ISSUE TITLE
SystemError: installArchives() failed

### ISSUE THREAD

**Issue by saxenam06** [demotomohiro/remocolab#104]
Hello, Could you please help me to solve the below error. I do the following in colab. 

!pip install git+https://github.com/demotomohiro/remocolab.git
import remocolab
remocolab.setupVNC()
 and get error as below. ManyThanks in advance. 
iblz4-1: Preparing to configure liblz4-1 (amd64)

E:Sub-process /usr/bin/dpkg returned an error code (1)

---------------------------------------------------------------------------

SystemError                               Traceback (most recent call last)

[<ipython-input-1-28a0dc8c2d39>](https://localhost:8080/#) in <module>()
      1 get_ipython().system('pip install git+https://github.com/demotomohiro/remocolab.git')
      2 import remocolab
----> 3 remocolab.setupVNC()

4 frames

[/usr/local/lib/python3.7/dist-packages/apt/cache.py](https://localhost:8080/#) in commit(self, fetch_progress, install_progress, allow_unauthenticated)
    679                         break
    680                     elif res == pm.RESULT_FAILED:
--> 681                         raise SystemError("installArchives() failed")
    682                     elif res == pm.RESULT_INCOMPLETE:
    683                         pass

SystemError: installArchives() failed

**Comment by suhassridhar** [comment]
Have been facing the exact same issue. It was working fine 3 days ago and has been showing SystemError now. Please someone help me fix the bug

**Comment by gkibria121** [comment]
> Have been facing the exact same issue. It was working fine 3 days ago and has been showing SystemError now. Please someone help me fix the bug

same thing happaning with me

**Comment by demotomohiro** [comment]
apt update && apt upgrade is failing.
Putting following line before you run remocolab.setupSSHD or remocolab.setupVNC fix the error:
```
!apt update && apt upgrade || apt --fix-broken install
```

**Comment by saxenam06** [comment]
It works! Thank you so much for a quick fix.
