### ISSUE TITLE
What about XRDP and teamviewer?

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#12]

**Comment by Rayanfer32** [comment]
xrdp works ... i have tried it myself .. go ahead and install it

**Comment by cdkfox** [comment]
> xrdp works ... i have tried it myself .. go ahead and install it

Do you have tutorials of how to set it up and using windows to connect it?

**Comment by demotomohiro** [comment]
TurboVNC and VirtualGL are used in remocolab because
- I can use OpenGL
- I can access the desktop from Linux/Windows/android
- communications are encrypted by using SSH port forwarding

Why do you want to use XRDP and teamviewer?
It seems hardware accelerated OpenGL is not supported by XRDP.

**Comment by cdkfox** [comment]
> TurboVNC and VirtualGL are used in remocolab because
> 
> * I can use OpenGL
> * I can access the desktop from Linux/Windows/android
> * communications are encrypted by using SSH port forwarding
> 
> Why do you want to use XRDP and teamviewer?
> It seems hardware accelerated OpenGL is not supported by XRDP.

First of all, I live in China, The connection to ngrok.com is not stable because we are behind the so called Great Firewall Of China aka GFW. But luckily, Teamviewer's Server is not blocked by GFW, so it would be much better to use teamviewer's remote desktop gateway as it is offers much more functionality and stability in China. 

Second, To my knowledge, the freerdp aka xrdp can stream sound via internet and offers much more performance over VNC server which basically send pictures over the internet. It would be much more user friendly and comfortable if we can use RDP protocol to use colab interactively I guess.

Third, I'm finding ways to install a linux virtual machine on the google colab environment. We can use teredo for a fixed ip address. Since colab is a container and doesn't support systemd. But it seems like the colab environment does not support KVM extension. Do you have any idea on this?

**Comment by Rayanfer32** [comment]
**Installing xrdp**
```
sudo apt install xrdp
sudo apt install xorg
sudo adduser xrdp ssl-cert
```
**open new terminal:**
`sudo xrdp-sesman -n`

**open new terminal:**
`sudo xrdp -n`
