### ISSUE TITLE
[Error]Kaggle: "Your notebook has been stopped by your request. If you just changed settings please wait while we reconfigure and restart your session."

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#17]
I opened a kaggle kernel without GPU or TPU and with Docker set to latest available. But it seems like kaggle detect that we are connecting to ngrok???

**Comment by cdkfox** [comment]
@demotomohiro Maybe our ngrok-own-server could solve the problem temporarily but why are they doing this, is that a violation of their tos?

**Comment by demotomohiro** [comment]
Could you post more details?
What code did you executed?

**Comment by demotomohiro** [comment]
I ran following code on both GPU and non GPU runtime on kaggle, but after execution completed, session was restart.

```
!pip install git+https://github.com/demotomohiro/remocolab.git@kaggle
import remocolab
remocolab.setupSSHD(check_gpu_available = False)
```

Same problem was reported here:
https://github.com/lamhoangtung/remokaggle/issues/3

If kaggle dont want us to run SSH server on it and login to it from remote PC, I don't do it.
