### ISSUE TITLE
[Help Wanted][Feature Request] Containers or Virtualizations on Google Colab?

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#19]
It seems like the google colab does not support VMX or container technology and this is not good for some developers who build stuff based on docker. Is there somehow another solution available for us?
@demotomohiro

**Comment by demotomohiro** [comment]
I tried to use docker on google colab before, but it seems we cannot run docker on docker.

**Comment by cdkfox** [comment]
> I tried to use docker on google colab before, but it seems we cannot run docker on docker.

I have tried it too, but it seems like junest is our only choice.https://github.com/fsquillace/junest but it seems like the namespace feature is disabled on linux but we can use --groot option, but somehow the junest cannot mount drives correctly. I'm not a linux system expert but I believe that we can somehow tweat the junest code a little bit to let it work on colab.

**Comment by cdkfox** [comment]
@demotomohiro Have you tried Domino Data Lab.

**Comment by demotomohiro** [comment]
@cdkfox I have never tried it.
