### ISSUE TITLE
[error]FetchFailedException: E:The repository 'https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ Release' no longer has a Release file.

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#20]
/usr/local/lib/python3.6/dist-packages/remocolab.py in setupVNC(ngrok_region)

/usr/local/lib/python3.6/dist-packages/remocolab.py in setupSSHD(ngrok_region, check_gpu_available)

/usr/local/lib/python3.6/dist-packages/remocolab.py in _setupSSHDImpl(ngrok_token, ngrok_region)

/usr/lib/python3/dist-packages/apt/cache.py in update(self, fetch_progress, pulse_interval, raise_on_error, sources_list)
    584                                              pulse_interval)
    585                 except SystemError as e:
--> 586                     raise FetchFailedException(e)
    587                 if not res and raise_on_error:
    588                     raise FetchFailedException()

FetchFailedException: E:The repository 'https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/ Release' no longer has a Release file.

**Comment by demotomohiro** [comment]
I got same error about 10 hours ago and it came from `apt update`.
But I don't get the error now.
