### ISSUE TITLE
Alternate/Automate the way to mount gdrive...

### ISSUE THREAD

**Issue by Rayanfer32** [demotomohiro/remocolab#21]
so i could spin up a VM and get started right away ..!!

**Comment by cdkfox** [comment]
I really don't think that you gonna need to mount gdrive in order to use the script. so I move that piece of code right into the bottom cell.

**Comment by cdkfox** [comment]
> so i could spin up a VM and get started right away ..!!

Sorry if that sounds harsh, but it seems too unnecessary to implement this feature. If you think so too, you should close the issue by now.

**Comment by Rayanfer32** [comment]
thats fine...i taught someone might know an alternative way to mount drive rather than oauth dance
