### ISSUE TITLE
[Urgent][Feature Request]Keep Colab Environment Running for 12 hours.

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#23]
Google Colab might shutdown our notebook compute instance once we leave the notebook, is there a way that we can keep the environment running without having to worry that the notebook might be suddenly shut down while we are working? According to the TOS, the maximum running time for a free colab instance is 12 hours. @demotomohiro

**Comment by cdkfox** [comment]
I guess the solution is that we can write some javascript code to click on the reconnect button after the connection is lost on colab.research.google.com

**Comment by Rayanfer32** [comment]
**Run this in browser console:** 
```javascript
function ClickConnect(){
console.log("Working"); 
document.querySelector("#top-toolbar > colab-connect-button").shadowRoot.querySelector("#connect").click()
} 
setInterval(ClickConnect,60000)
```
