### ISSUE TITLE
[Feature Request]Azure Notebooks Preview Support with Junest Environment

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#24]
Microsoft Azure Notebooks supports Linux namespace feature (nc) which google colab DOES NOT. We can install junest environment https://github.com/fsquillace/junest and use millions of newest software from Arch Linux User Repositories faster by using yaourt or yay or Pacman. Azure Notebooks are not blocked by the Chinese firewall in china thus it is much easier to use than google colab. @demotomohiro 

If we install junest in google colab, it will fail like this:

> bwrap: pivot_root: Operation not permitted
> Error: Something went wrong while executing bwrap command. Exiting

But on the azure notebook, junest runs perfectly normal. 

Free Azure Notebook also runs more stable than google colab since they don't disconnect you after 1 hour of inactivity on the webpage and can guarantee to run for at least 8 hours.

The other thing is that you can get a web shell access which google colab is unable to provide.

But the downside is that the bandwidth and memory are far more restricted than google colab.

Please implement this feature, and another thing is that when we are working in azure notebooks, everything in ~/library directory is under rotational hard drive but the home directory is under Solid States Drive. We should install the ngrok and junest under the home directory for the best performance.

@demotomohiro

**Comment by cdkfox** [comment]
@Rayanfer32 Do you have any ideas on this?

**Comment by demotomohiro** [comment]
Making remocolab works in both google colab and azure notebooks we have to test it on 2 service everytime we add new feature or fixing bugs.
I want a way to test remocolab automatically.
I tested remocolab on https://notebooks.azure.com/ they don't have a `apt` python module.

**Comment by Rayanfer32** [comment]
it also don't allow sudo right...?

**Comment by cdkfox** [comment]
@demotomohiro @Rayanfer32 Yes they don't allow sudo but they do allow running junest environment which allows us to run sudo commands.

**Comment by Rayanfer32** [comment]
> 
> 
> @demotomohiro @Rayanfer32 Yes they don't allow sudo but they do allow running junest environment which allows us to run sudo commands.

Then there is a hope ... we just need to aim at it

**Comment by Rayanfer32** [comment]
https://stackoverflow.com/questions/44996933/using-sudo-inside-jupyter-notebooks-cell

have a look at this, will this work out

**Comment by Rayanfer32** [comment]
@cdkfox Can you share your progress or a copy of your junest notebook ... i'm just new to junest

**Comment by cdkfox** [comment]
> @cdkfox Can you share your progress or a copy of your junest notebook ... i'm just new to junest

* Install Junest
```sh
git clone git://github.com/fsquillace/junest ~/.local/share/junest
export PATH=~/.local/share/junest/bin:$PATH
junest setup
junest
```
* Install shadowsocks-libev
```sh
sudo pacman -Syy
sudo pacman -S --noconfirm wget tar shadowsocks-libev 
```

**Comment by Rayanfer32** [comment]
installed junest using terminal and inside it 

**there is no apt
there is no wget( curl is present)
there is no dpkg**

What ive found so far,
https://unix.stackexchange.com/questions/282224/how-to-extract-and-install-deb-without-the-command-dpkg

**Comment by cdkfox** [comment]
> installed junest using terminal and inside it
> 
> **there is no apt there is no wget( curl is present) there is no dpkg**
> 
> What ive found so far,
> https://unix.stackexchange.com/questions/282224/how-to-extract-and-install-deb-without-the-command-dpkg

Junest is a archlinux based linux, pacman, yay and yaourt are the apt-get. By the way, pacman repositories contains way more packages than apt. If you don't have experience with ArchLinux, you should really spend some time trying it out. It has some features that are much better than ubuntu.

**Comment by Rayanfer32** [comment]
ohh... yes i will try it out...but which point of installing xfce u got
stuck

**Comment by cdkfox** [comment]
@Rayanfer32 I am planning to make a remoazurenotebook repo specifically for supporting azure notebook users, let's not make a mess here

**Comment by Rayanfer32** [comment]
that will be cool😎
