### ISSUE TITLE
Add `ngrok_token` parameter to the `setupSSHD()` function and don't prompt for GPU runtime checking.

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#26]

**Comment by demotomohiro** [comment]
ngrok token must be kept secret.
If you can specify ngrok token to remocolab.setupSSHD() or remocolab.setupVNC(), you can save ngrok token to a notebook.
Then, you might forget that your notebook contains it and share the notebook.
I understand people hate copy & pasting ngrok token everytime they use remocolab, but I don't know how to skip it without risking a security.

Pass `check_gpu_available = False` to `setupSSHD()`.

**Comment by cdkfox** [comment]
> ngrok token must be kept secret.
> If you can specify ngrok token to remocolab.setupSSHD() or remocolab.setupVNC(), you can save ngrok token to a notebook.
> Then, you might forget that your notebook contains it and share the notebook.
> I understand people hate copy & pasting ngrok token everytime they use remocolab, but I don't know how to skip it without risking a security.
> 
> Pass `check_gpu_available = False` to `setupSSHD()`.

Kaggle has this feature to set a secret field in notebook but unfortunately google colab doesn't.
