### ISSUE TITLE
"Permission Denied" error with root user

### ISSUE THREAD

**Issue by xyzPrimeTV** [demotomohiro/remocolab#27]
I am not able to login with root user...it is throwing error as "Permission Denied"..."Colab" user is working fine.

Thanks in advance for any help...

**Comment by demotomohiro** [comment]
You can login as root using public key authentication:
https://github.com/demotomohiro/remocolab#how-to-setup-public-key-authentication

Or use `su` command.

**Comment by xyzPrimeTV** [comment]
Thanks...It is working fine with public key...
