### ISSUE TITLE
Password are way lengthy

### ISSUE THREAD

**Issue by Rayanfer32** [demotomohiro/remocolab#3]
on windows thhere is no ssh client ... i use git bash ..... problem is when i copy the pass some formatting is done ... it fails most of the time ... plz reduce the password size if possible ... thanks

**Comment by demotomohiro** [comment]
I'm using ssh client that is installed with [Scoop](https://scoop.sh/) on windows.
Copy & pasting password always works.
I installed it with `scoop install openssh` after installing scoop.

If you setup Public key authentication, you can login without passwords.
Please see https://github.com/demotomohiro/remocolab/pull/2#issuecomment-546579840

**Comment by Rayanfer32** [comment]
for convenience i forked your code and assigned a easy passwrd
thanks anyway ... tutorial is great

**Comment by demotomohiro** [comment]
I read your forked repo and you replaced the passwords to too easy ones.
When you setup SSH server using remocolab, anyone can try to connect it from the internet.
Anyone can read your source code in your public Github repository.
If you really need to use such a simple passwords, you should disable password authentication by adding `PasswordAuthentication no` to `/etc/ssh/sshd_config` and use public key authentication only.

**Comment by Rayanfer32** [comment]
Oh yea thats there.... but what are the chances... docker container will
die in 12hrs and ports also change frequently... so i made it easy
