### ISSUE TITLE
Change ssh to mosh. 

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#33]
Mosh never drop ssh connection when we change wifi aps.

**Comment by demotomohiro** [comment]
[mosh](https://mosh.org/) uses UDP protocol but ngrok doesn't support UDP.
https://github.com/inconshreveable/ngrok/issues/26

**Comment by cdkfox** [comment]
We can install a socks5 proxy which supports udp

**Comment by cdkfox** [comment]
L we don't have to do that because  m o s h does not support forwarding
