### ISSUE TITLE
Error when running colab.

### ISSUE THREAD

**Issue by cdkfox** [demotomohiro/remocolab#45]
openssh-server is already installed
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-38a3c26ae0a4> in <module>()
     10 get_ipython().system('pip install git+https://github.com/demotomohiro/remocolab.git')
     11 import remocolab
---> 12 remocolab.setupVNC(ngrok_region="us", check_gpu_available=False)
     13 
     14 

5 frames
/usr/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1293                             errread, errwrite,
   1294                             errpipe_read, errpipe_write,
-> 1295                             restore_signals, start_new_session, preexec_fn)
   1296                     self._child_created = True
   1297                 finally:

TypeError: expected str, bytes or os.PathLike object, not dict

**Comment by demotomohiro** [comment]
I don't get such error.
Could you tell me how did you got such error?

**Comment by cdkfox** [comment]
I don't have this problem when I'm not on the GPU, but once I'm on the GPU, the program reports the error

**Comment by demotomohiro** [comment]
As you can run only 1 ngrok process with free ngrok account, running `remocolab.setupVNC/setupSSHD` will fail if there is another instace that already ran remocolab.
In that case, terminate another instance from `Manage sessions` screen.
