### ISSUE TITLE
colab@0.tcp.in.ngrok.io: Permission denied (publickey,password).

### ISSUE THREAD

**Issue by bender2po** [demotomohiro/remocolab#52]
Hi,
I have used remocolab a couple of weeks back. I was successfully connected to VM instance using VNC. 
I am trying to replicate the same scenario, however, I am not successful this time. I could not successfully execute 9th step of "README.md".
When I copy pasted (cntr+v) the password in command-prompt, it is giving following error after 3 failed attempts:
'colab@0.tcp.in.ngrok.io: Permission denied (publickey,password).'

Any help would be appreciated. Thank you!

**Comment by demotomohiro** [comment]
Do you get same error when you use ssh to login to other server?
I that case, your ssh config file might have problem or you might need to reinstall ssh.

Do you run other code before/after `remocolab.setupVNC()`?

**Comment by bender2po** [comment]
> 
> 
> Do you get same error when you use ssh to login to other server?
Yes
> I that case, your ssh config file might have problem or you might need to reinstall ssh.
I unistalled ssh. but failed to install again tried for hours.
this is what i get
![image](https://user-images.githubusercontent.com/66256684/85602858-69be6f80-b66d-11ea-86a8-3ceb584d65e6.png)
> 
> Do you run other code before/after `remocolab.setupVNC()`?
I don't run any extra code. I just run the three lines
"!pip install git+https://github.com/demotomohiro/remocolab.git
import remocolab
remocolab.setupVNC()"

**Comment by demotomohiro** [comment]
How about to google these error message?

**Comment by bender2po** [comment]
> 
> 
> How about to google these error message?

Finally, I re-installed ssh. however, same issue persists:
![image](https://user-images.githubusercontent.com/66256684/85651583-17f60380-b6c6-11ea-9dae-4d0c0926b3f5.png)

**Comment by demotomohiro** [comment]
Running ssh command with `-v` option show more details.

If you get same error when you use ssh to login to other server, that means this is problem of your ssh client or your PC.
As you looks like using OpenSSH in Windows, I think you should report this problem to https://github.com/PowerShell/openssh-portable

**Comment by bender2po** [comment]
> 
> 
> Running ssh command with `-v` option show more details.
> 
> If you get same error when you use ssh to login to other server, that means this is problem of your ssh client or your PC.
> As you looks like using OpenSSH in Windows, I think you should report this problem to https://github.com/PowerShell/openssh-portable

Thank you for your response. Looks like this issue is just for my PC. I will try as you suggested and post if anything fruitful happens.
Closing issue now.
