### ISSUE TITLE
Unable to enable ssh port forwarding

### ISSUE THREAD

**Issue by xd003** [demotomohiro/remocolab#55]
As mentioned in readme , i first connect to ssh , then enter the colab password ,ssh connects well

Now i run the vnc command inside colab ssh ,  it immediately gives me the following error ..

```
colab@0.tcp.in.ngrok.io's password: 
bind: Cannot assign requested address
channel_setup_fwd_listener_tcpip: cannot listen to port: 5901
Could not request local forwarding.
```

please fix this issue

**Comment by demotomohiro** [comment]
I think you are running commands in wrong way.
I will rewrite "How to use" part in ``Readme.md`` more clearly.

After ``remocolab.setupVNC()`` you need to run the ssh command under ``If you use VNC:`` in your local PC, not under ``Command to connect to the ssh server:``.
After login to colab server, you can run TurboVNC viewer on your local machine.
You don't need to run any command after logined to the server.

I also wrote how to use VNC in my blog post:
https://internet-of-tomohiro.netlify.app/google_colab/vnc.en.html
