### ISSUE TITLE
Getting ssh error

### ISSUE THREAD

**Issue by awanish091** [demotomohiro/remocolab#56]
Collecting git+https://github.com/demotomohiro/remocolab.git
  Cloning https://github.com/demotomohiro/remocolab.git to /tmp/pip-req-build-rjdhct4h
  Running command git clone -q https://github.com/demotomohiro/remocolab.git /tmp/pip-req-build-rjdhct4h
Building wheels for collected packages: remocolab.py
  Building wheel for remocolab.py (setup.py) ... done
  Created wheel for remocolab.py: filename=remocolab.py-0.1-cp36-none-any.whl size=6283 sha256=d70228dceac82fb367f6adae386d9e0e20ac9f3565cad9148d39233a93477840
  Stored in directory: /tmp/pip-ephem-wheel-cache-o7ho3121/wheels/9e/c3/02/22e12a4614e679c5555718bd4d0356e4b7cc1d69a1f3ddb564
Successfully built remocolab.py
Installing collected packages: remocolab.py
Successfully installed remocolab.py-0.1
This is not a runtime with GPU
Do you want to continue? [y/n] y
---
Copy&paste your tunnel authtoken from https://dashboard.ngrok.com/auth
(You need to sign up for ngrok and login,)
··········
Select your ngrok region:
us - United States (Ohio)
eu - Europe (Frankfurt)
ap - Asia/Pacific (Singapore)
au - Australia (Sydney)
sa - South America (Sao Paulo)
jp - Japan (Tokyo)
in - India (Mumbai)
in
Install openssh-server
Failed to download  https://astuteinternet.dl.sourceforge.net/project/libjpeg-turbo/2.0.4/libjpeg-turbo-official_2.0.4_amd64.deb
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1324                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error

19 frames
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error
-> 1327                 raise URLError(err)
   1328             r = h.getresponse()
   1329         except:

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

**Comment by demotomohiro** [comment]
Download URL for TurboVNC used in remocolab stop working.
I fixed it in https://github.com/demotomohiro/remocolab/pull/57.

**Comment by demotomohiro** [comment]
Do you still get any errors?

**Comment by awanish091** [comment]
No - now it's working completely fine

**Comment by awanish091** [comment]
Thanks
