### ISSUE TITLE
New 2nd connection

### ISSUE THREAD

**Issue by stefanjuang** [demotomohiro/remocolab#58]
May I know what I would need to change to start multiple connections to VNC?
Example: I started two colabs, both ran remocolab.
The first can be connected to VNC through localhost:1
While the second cannot.

(Where can we change the server address parameter?)

Thanks

**Comment by demotomohiro** [comment]
You can connect to multiple TurboVNC servers by changing the local port part of -L option when you run second ssh command for port forwarding.
For example, change `-L 5901:localhost:5901` to `-L 5902:localhost:5901` and specify `localhost:2` on VNC viewer.

**Comment by stefanjuang** [comment]
Got it!
Thank you 👍
