### ISSUE TITLE
Stuck at Welcom Screen

### ISSUE THREAD

**Issue by dshot92** [demotomohiro/remocolab#65]
## There might be a hint to solve your problem in [FAQ](https://github.com/demotomohiro/remocolab/wiki/Frequently-Asked-Questions)

**Describe the bug**
When i log into VNC connection i cannot control the machine.
No mouse click or keyboard input are displayed inside the virtual machine
Hard stuck at intro screen of the xcfe enviorment prompting to setup display option for panels

![](https://gist.github.com/demotomohiro/53d631aaf5b9680ddaefa55a98b1ac60/raw/99fbf1cb0aea4896fcb9cadf2e9758bfb7b7561b/googlecolab_vnc_first_screen.png)

**To Reproduce**
Follow exact steps as tutorial

No extra code runned into google colab file

**Expected behavior**
Being able to use the vm

**Desktop (please complete the following information):**
 - OS: windows 10 / ubuntu 18.04
 - Chrome
- TurboVNC

**Comment by demotomohiro** [comment]
`remocolab.setupVNC()` show 2 VNC passwords and second one is view only password.

For example:
```
VNC password: xxxxxxxx
VNC view only password: yyyyyyyy
```

You should be able to control the destkop if you login into VNC by using first VNC password.
If you use second password to login, you can see the destkop but cannot control the desktop.

**Comment by dshot92** [comment]
> `remocolab.setupVNC()` show 2 VNC passwords and second one is view only password.
> 
> For example:
> 
> ```
> VNC password: xxxxxxxx
> VNC view only password: yyyyyyyy
> ```
> 
> You should be able to control the destkop if you login into VNC by using first VNC password.
> If you use second password to login, you can see the destkop but cannot control the desktop.

Thank you.  Did not notice that.
