### ISSUE TITLE
Can we make a trick to transmit audio also... 

### ISSUE THREAD

**Issue by Rayanfer32** [demotomohiro/remocolab#7]
this would be helpul for audio related projects

**Comment by demotomohiro** [comment]
TurboVNC doesn't transmit audio.
I think you need to install some software that transmit audio.

**Comment by Rayanfer32** [comment]
`sudo apt install anydesk` (if u need audio too)

**Comment by Rayanfer32** [comment]
Chrome Remote Desktop Transmits audio ... you just need to create a
host.json file once with your gmail account.
