### ISSUE TITLE
Unable to interact through VNC

### ISSUE THREAD

**Issue by arnish12345** [demotomohiro/remocolab#74]
Everything works fine but when I click on the icons or on the "use default config" of the "welcome to the first start of the panel" window, nothing happens ! ☹

**Comment by ochen1** [comment]
Weird, this never happened with me. Did you use the correct VNC password?
Remocolab givese 2 passwords, one for interacting, and another one for solely viewing. Please make sure that you are using the interacting one.

Sincerely,
Happy Remocolab User

**Comment by arnish12345** [comment]
Lol, used the second one. Thx for letting me know!
