### ISSUE TITLE
no root support in desktop environment

### ISSUE THREAD

**Issue by Rayanfer32** [demotomohiro/remocolab#8]
cannot login as root user in xfce .. i cannot access Gdrive folders in thunar file browser after mounting

found a thread here http://en.freelander.es/2011/05/21/xfce-root-login/
**> Open a terminal and, as root, edit the file /etc/pam.d/gdm3. Comment out the line that says: “auth required pam_succeed_if.so user != root quiet success”**

**Comment by demotomohiro** [comment]
I cannot run TurboVNC as root user.
You can become root on console using `su` command and you can do `ls` or `cd` to the mounted gdrive.

**Comment by Rayanfer32** [comment]
yea but is it possible to run turbovnc as root...

**Comment by demotomohiro** [comment]
When I tried to run TurboVNC server as root on google colab, it show error.
I think there is a security reason behind why TurboVNC server or xfce doesn't run as root.

**Comment by Rayanfer32** [comment]
for temporary fix  use ``sudo thunar`` it works
