### ISSUE TITLE
transfer downloaded

### ISSUE THREAD

**Issue by D-EVE-R** [demotomohiro/remocolab#86]
hello, thanks for this awesome work, am asking if there is any way to transfer downloaded files to my machine or even download it directly. thank you

**Comment by demotomohiro** [comment]
You can download/upload files using google drive.
https://github.com/demotomohiro/remocolab#how-to-mount-google-drive

**Comment by D-EVE-R** [comment]
thanks for ur reply. yeah am already using it, but it's kinda useless to download something twice, especially when you download with high speed and redownload it with a low speed, I want to use that high-speed down/upload advantage.

**Comment by demotomohiro** [comment]
Please you make your question more precise.
Do you want to download files from some server to your google colab instance via internet or download from your google colab instance to your local machine?
Another way to download files from your google colab instance to your local machine is using [scp](https://man.openbsd.org/scp) or [sshfs](https://github.com/libfuse/sshfs).

**Comment by D-EVE-R** [comment]
yes exactly I want to download files from collab to my machine, I have tried using SCP but am struggling with what to put in the user@host. and the script only provides these credentials to get connected (ssh -o UserKnownHostsFile=/dev/null -o VisualHostKey=yes -oProxyCommand="cloudflared access ssh --hostname %h" -L 5901:localhost:5901 colab@renewal-charlotte-everyone-strictly.trycloudflare.com).

**Comment by demotomohiro** [comment]
If remocolab printed following ssh command,
```
ssh -o UserKnownHostsFile=/dev/null -o VisualHostKey=yes -oProxyCommand="cloudflared access ssh --hostname %h" colab@renewal-charlotte-everyone-strictly.trycloudflare.com
```
You can download file `xyz` in colab user home directory with following command:
```
scp -o UserKnownHostsFile=/dev/null -o VisualHostKey=yes -oProxyCommand="cloudflared access ssh --hostname %h" colab@capitol-ladder-peru-driven.trycloudflare.com:xyz .
```

**Comment by D-EVE-R** [comment]
thanks a lot, that was helpful I have been using the hole command, but now I noticed that I should remove the -L 5901:localhost:5901 flag.
