### ISSUE TITLE
websocket: bad handshake ssh_exchange_identification: Connection closed by remote host

### ISSUE THREAD

**Issue by real-Piyush-Sharma** [demotomohiro/remocolab#87]
```
websocket: bad handshake 
ssh_exchange_identification: Connection closed by remote host
```

**Describe the bug**
On trying to connect to ssh session using argo, it fails with the following issue.
```
websocket: bad handshake 
ssh_exchange_identification: Connection closed by remote host
```

**To Reproduce**
It occurs on simply trying to connect to ssh.

Any code that is executed before or after remocolab's setup code.

**Expected behavior**

![image](https://user-images.githubusercontent.com/47710035/104302015-4dd9c880-54ee-11eb-82a5-a872adb5f161.png)

**Desktop**
 - OS: Windows 10
 - Browser Chrome

**Comment by sasagr** [comment]
same here

**Comment by Rayanfer32** [comment]
Cloudflare takes 5 mins sometimes to properly establish the connection.

**Comment by demotomohiro** [comment]
Sometimes, doing "factory reset runtime" and try again works.
Do you get any reply with ping command like `ping your-random-server-address.trycloudflare.com`?
If you got reply, probably argo tunnel is working and maybe some ssh client settings need to be fixed.
If you don't get any reply, maybe argo tunnel take long time to become accessible or cloudflare is not providing their service in your region.

**Comment by sasagr** [comment]
it seems to be working fine right now. I believe it was something temporary
