### ISSUE TITLE
Cannot run software from gdrive directly

### ISSUE THREAD

**Issue by Rayanfer32** [demotomohiro/remocolab#9]
`Running Firefox as root in a regular user's session is not supported.`
gdrive cannot be accessed unless sudo

if i login as root in terminal and excute/run apps  as 
`firefox`

i get
 `ERROR :"cannot open display” error`
  

`

**Comment by demotomohiro** [comment]
Are they issues of remocolab?
Are they not issues of ubuntu, xfce or gdrive?

**Comment by Rayanfer32** [comment]
yes... they are issue related to xfce... but is there some other method to run apps from root
