### ISSUE TITLE
When I use GPU on colab, some environment variables are missed

### ISSUE THREAD

**Issue by Shuntw6096** [demotomohiro/remocolab#91]
Hi,
as the title says, when I use `nvidia-smi` , it return `Failed to initialize NVML: Driver/library version mismatch`, and use `nvcc -V`, it does not work, I use `remocolab.setupSSHD(check_gpu_available=True)` to set ssh environment.
Thanks

**Comment by demotomohiro** [comment]
`nvidia-smi` and `nvcc -V` worked from ssh by running following code on colab after `remocolab.setupSSHD()`

```
!echo export NVIDIA_DRIVER_CAPABILITIES=\"$NVIDIA_DRIVER_CAPABILITIES\" >> /home/colab/.bashrc
!echo export NVIDIA_REQUIRE_CUDA=\"$NVIDIA_REQUIRE_CUDA\" >> /home/colab/.bashrc
!echo export NVIDIA_VISIBLE_DEVICES=\"$NVIDIA_VISIBLE_DEVICES\" >> /home/colab/.bashrc
!echo export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\" >> /home/colab/.bashrc
!echo export PATH=\"/usr/local/nvidia/bin:/usr/local/cuda/bin:\$PATH\" >> /home/colab/.bashrc
```

**Comment by Shuntw6096** [comment]
It works, thanks.
> `nvidia-smi` and `nvcc -V` worked from ssh by running following code on colab after `remocolab.setupSSHD()`
> 
> ```
> !echo export NVIDIA_DRIVER_CAPABILITIES=\"$NVIDIA_DRIVER_CAPABILITIES\" >> /home/colab/.bashrc
> !echo export NVIDIA_REQUIRE_CUDA=\"$NVIDIA_REQUIRE_CUDA\" >> /home/colab/.bashrc
> !echo export NVIDIA_VISIBLE_DEVICES=\"$NVIDIA_VISIBLE_DEVICES\" >> /home/colab/.bashrc
> !echo export LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\" >> /home/colab/.bashrc
> !echo export PATH=\"/usr/local/nvidia/bin:/usr/local/cuda/bin:\$PATH\" >> /home/colab/.bashrc
> ```
