### ISSUE TITLE
It doesn't work, runtime disconnects

### ISSUE THREAD

**Issue by schissmantics** [demotomohiro/remocolab#98]
I tried on many occasions, and I always end up by being disconnected within minutes of the setup after running:

    !pip install git+https://github.com/demotomohiro/remocolab.git
    import remocolab
    remocolab.setupVNC()

or 

    remocolab.setupVNC(tunnel = 'argotunnel', public_key = '...')

So far I have tried using multiple accounts, and all of them are gpu-restricted ever since.

**Comment by demotomohiro** [comment]
Please read this:
https://github.com/demotomohiro/remocolab/wiki/Frequently-Asked-Questions#google-colab-disconnected-before-or-right-after-remocolabsetupvnc-done

Do you still get disconnected within minutes even if you run a simple python3 code that do not use remocolab like this?

```python3
import time

begin = time.time()
for i in range(30 * 6):
  time.sleep(10)
  print(time.time() - begin)
```

**Comment by alok-debnath** [comment]
> Do you still get disconnected within minutes even if you run a simple python3 code that do not use remocolab like this?

No, it doesn't disconnects while running this code.

**Comment by schissmantics** [comment]
I was able to run python code and remocolab code, and it works fine without any particular changes I made therefore I'll close the issue.

**Comment by demotomohiro** [comment]
No, you don't need to do it.
Sometimes colab disconnects after running a cell about 5~10 minutes regardless of what the code do.
I don't know how to fix it. Sometimes, it fixed after a few days.
Maybe, colab trys to allocate more machines for paid user by disconnecting a machine for free user.
